# Generated by Django 5.0.14 on 2026-01-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_vouchersalesinvoicedetails_vouchersalesewaybill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('voucher_type', models.CharField(default='Payment', max_length=50)),
                ('voucher_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_from', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_to', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(choices=[('single', 'Single'), ('bulk', 'Bulk')], default='single', max_length=20)),
                ('posting_note', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
            options={
                'db_table': 'voucher_payment',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherPaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pay_to', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_date', models.DateField(blank=True, null=True)),
                ('is_advance', models.BooleanField(default=False)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.voucherpayment')),
            ],
            options={
                'db_table': 'voucher_payment_lines',
            },
        ),
    ]
