# Generated by Django 5.0.14 on 2026-01-24 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_voucherpayment_voucherpaymentline'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPaymentBulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('voucher_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_from', models.CharField(blank=True, max_length=255, null=True)),
                ('posting_note', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
            options={
                'verbose_name': 'Payment Voucher (Bulk)',
                'db_table': 'voucher_payment_bulk',
            },
        ),
        migrations.CreateModel(
            name='VoucherPaymentSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('voucher_type', models.CharField(default='Payment', max_length=50)),
                ('voucher_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_from', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_to', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
            options={
                'verbose_name': 'Payment Voucher (Single)',
                'db_table': 'voucher_payment_single',
            },
        ),
        migrations.RemoveField(
            model_name='voucherpaymentline',
            name='voucher',
        ),
        migrations.CreateModel(
            name='VoucherPaymentBulkAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('advance_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('pay_to', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_bulk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='accounting.voucherpaymentbulk')),
            ],
            options={
                'db_table': 'voucher_payment_bulk_advances',
            },
        ),
        migrations.CreateModel(
            name='VoucherPaymentBulkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pay_to', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('payment_bulk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.voucherpaymentbulk')),
            ],
            options={
                'db_table': 'voucher_payment_bulk_items',
            },
        ),
        migrations.CreateModel(
            name='VoucherPaymentSingleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('txn_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('payment_single', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.voucherpaymentsingle')),
            ],
            options={
                'db_table': 'voucher_payment_single_allocations',
            },
        ),
        migrations.DeleteModel(
            name='VoucherPayment',
        ),
        migrations.DeleteModel(
            name='VoucherPaymentLine',
        ),
    ]
