# Generated by Django 5.0.14 on 2025-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_voucher_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('type', models.CharField(choices=[('LedgerGroup', 'Ledger Group'), ('Ledger', 'Ledger'), ('Voucher', 'Voucher')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('under', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_type', models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered'), ('Composition', 'Composition')], max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_prefix', models.CharField(blank=True, help_text='e.g. INV-', max_length=50, null=True)),
                ('sales_suffix', models.CharField(blank=True, help_text='e.g. /24-25', max_length=50, null=True)),
                ('sales_next_number', models.PositiveBigIntegerField(default=1, help_text='next seq')),
                ('sales_padding', models.IntegerField(default=4, help_text='digit padding')),
                ('sales_preview', models.CharField(blank=True, help_text='computed preview', max_length=255, null=True)),
                ('purchase_prefix', models.CharField(blank=True, help_text='e.g. PO-', max_length=50, null=True)),
                ('purchase_suffix', models.CharField(blank=True, help_text='e.g. /24-25', max_length=50, null=True)),
                ('purchase_next_number', models.PositiveBigIntegerField(default=1, help_text='next seq')),
                ('purchase_padding', models.IntegerField(default=4, help_text='digit padding')),
                ('purchase_preview', models.CharField(blank=True, help_text='computed preview', max_length=255, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, help_text='user id who last updated masters UI', null=True)),
                ('masters_meta', models.JSONField(blank=True, help_text='optional metadata for UI', null=True)),
            ],
            options={
                'db_table': 'masters',
            },
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='group',
        ),
        migrations.AlterField(
            model_name='voucherline',
            name='ledger',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='VoucherNumbering',
        ),
        migrations.RemoveConstraint(
            model_name='vouchertype',
            name='unique_voucher_type_name_tenant',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='voucher_number',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='image',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='voucher_type',
        ),
        migrations.RemoveField(
            model_name='voucherline',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='voucherline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='voucherline',
            name='type',
        ),
        migrations.RemoveField(
            model_name='voucherline',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='voucher',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_inter_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='tenant_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='voucherline',
            name='tenant_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name='vouchertype',
            unique_together={('name', 'tenant_id')},
        ),
        migrations.AlterModelTable(
            name='voucher',
            table='vouchers',
        ),
        migrations.AlterModelTable(
            name='voucherline',
            table='journal_entries',
        ),
        migrations.CreateModel(
            name='VoucherMaster',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.master',),
        ),
        migrations.DeleteModel(
            name='AccountGroup',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.master',),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.master',),
        ),
    ]
