# Generated by Django 5.0.14 on 2026-01-24 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_voucherpaymentbulk_voucherpaymentsingle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherpaymentbulkitem',
            name='payment_bulk',
        ),
        migrations.RemoveField(
            model_name='voucherpaymentsingleallocation',
            name='payment_single',
        ),
        migrations.AlterModelOptions(
            name='voucherpaymentbulk',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='voucherpaymentsingle',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='voucherpaymentbulk',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='voucherpaymentsingle',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='voucherpaymentbulk',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherpaymentbulk',
            name='advance_ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucherpaymentbulk',
            name='payment_rows',
            field=models.JSONField(blank=True, help_text='List of vendors and amounts to pay', null=True),
        ),
        migrations.AddField(
            model_name='voucherpaymentbulk',
            name='transaction_details',
            field=models.JSONField(blank=True, help_text='List of specific transactions paid in bulk mode', null=True),
        ),
        migrations.AddField(
            model_name='voucherpaymentsingle',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherpaymentsingle',
            name='transaction_details',
            field=models.JSONField(blank=True, help_text='List of pending transactions with payment amounts', null=True),
        ),
        migrations.AlterField(
            model_name='voucherpaymentbulk',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucherpaymentbulk',
            name='pay_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucherpaymentbulk',
            name='voucher_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucherpaymentsingle',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucherpaymentsingle',
            name='pay_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucherpaymentsingle',
            name='voucher_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucherpaymentsingle',
            name='voucher_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='VoucherPaymentBulkAdvance',
        ),
        migrations.DeleteModel(
            name='VoucherPaymentBulkItem',
        ),
        migrations.DeleteModel(
            name='VoucherPaymentSingleAllocation',
        ),
    ]
