# Generated by Django 5.0.14 on 2026-01-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_voucherpaymentbulkitem_payment_bulk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpaymentbulk',
            name='transaction_details',
            field=models.JSONField(blank=True, help_text='List of transactions: [{date, invoiceNo, amount, payNow, pending, advance}]', null=True),
        ),
        migrations.AlterField(
            model_name='voucherpaymentsingle',
            name='transaction_details',
            field=models.JSONField(blank=True, help_text='List of transactions: [{date, referenceNumber, amount, payment, pending, advance}]', null=True),
        ),
    ]
