# Generated by Django 5.0.14 on 2025-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_fix_journal_entries_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='items_data',
            field=models.JSONField(blank=True, help_text='Store UI line items (qty, rate, etc)', null=True),
        ),
    ]
