# Generated by Django 5.0.14 on 2025-12-20 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_voucher_items_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'journal_entries',
            },
        ),
        migrations.CreateModel(
            name='MasterLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(help_text='Ledger group name', max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_type', models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered'), ('Composition', 'Composition')], max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'master_ledgers',
            },
        ),
        migrations.CreateModel(
            name='MasterLedgerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.CharField(blank=True, help_text='Parent group name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'master_ledger_groups',
            },
        ),
        migrations.CreateModel(
            name='MasterVoucherConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='__NUMBERING__', max_length=255)),
                ('sales_enable_auto', models.BooleanField(default=True)),
                ('sales_prefix', models.CharField(blank=True, help_text='e.g. INV-', max_length=50, null=True)),
                ('sales_suffix', models.CharField(blank=True, help_text='e.g. /24-25', max_length=50, null=True)),
                ('sales_next_number', models.PositiveBigIntegerField(default=1)),
                ('sales_padding', models.IntegerField(default=4)),
                ('sales_preview', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_enable_auto', models.BooleanField(default=True)),
                ('purchase_prefix', models.CharField(blank=True, help_text='e.g. PO-', max_length=50, null=True)),
                ('purchase_suffix', models.CharField(blank=True, help_text='e.g. /24-25', max_length=50, null=True)),
                ('purchase_next_number', models.PositiveBigIntegerField(default=1)),
                ('purchase_padding', models.IntegerField(default=4)),
                ('purchase_preview', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'master_voucher_config',
            },
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.RemoveField(
            model_name='voucherline',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='VoucherType',
        ),
        migrations.DeleteModel(
            name='AccountGroup',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='VoucherMaster',
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='from_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='to_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='account',
            field=models.CharField(blank=True, help_text='Payment/Receipt account (Cash/Bank)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_inter_state',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='items_data',
            field=models.JSONField(blank=True, help_text='Line items with qty, rate, etc', null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('contra', 'Contra'), ('journal', 'Journal')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('voucher_number', 'tenant_id', 'type')},
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['type', 'tenant_id', 'date'], name='vouchers_type_567f73_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['tenant_id', 'date'], name='vouchers_tenant__6180d8_idx'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.voucher'),
        ),
        migrations.AlterUniqueTogether(
            name='masterledger',
            unique_together={('name', 'tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='masterledgergroup',
            unique_together={('name', 'tenant_id')},
        ),
        migrations.DeleteModel(
            name='VoucherLine',
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['voucher', 'tenant_id'], name='journal_ent_voucher_73bcf1_idx'),
        ),
    ]
