# Generated by Django 5.0.14 on 2026-01-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_voucherpaymentbulk_transaction_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherReceiptBulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=100)),
                ('receive_in', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_rows', models.JSONField(blank=True, help_text='List of customers and amounts to receive', null=True)),
                ('posting_note', models.TextField(blank=True, null=True)),
                ('advance_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_details', models.JSONField(blank=True, help_text='List of transactions: [{date, invoiceNo, amount, receiveNow, pending, advance}]', null=True)),
            ],
            options={
                'db_table': 'voucher_receipt_bulk',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherReceiptSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('voucher_type', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher_number', models.CharField(max_length=100)),
                ('receive_in', models.CharField(blank=True, max_length=100, null=True)),
                ('receive_from', models.CharField(blank=True, max_length=255, null=True)),
                ('total_receipt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_details', models.JSONField(blank=True, help_text='List of transactions: [{date, referenceNumber, amount, receipt, pending, advance}]', null=True)),
            ],
            options={
                'db_table': 'voucher_receipt_single',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
