# Generated by Django 5.0.14 on 2026-01-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_voucherreceiptbulk_voucherreceiptsingle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=100)),
                ('expense_rows', models.JSONField(default=list, help_text='List of expense entries')),
                ('uploaded_files', models.JSONField(blank=True, default=list, help_text=' List of uploaded supporting document filenames')),
            ],
            options={
                'db_table': 'voucher_expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
