# Generated by Django 5.0.14 on 2026-01-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_voucherexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherexpense',
            name='posting_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
