# Generated by Django 5.0.14 on 2026-01-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_voucherexpense_posting_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='exchange_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='export_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='outward_slip_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vouchersalesinvoicedetails',
            name='voucher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
