# Generated by Django 5.0.14 on 2026-01-25 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_vouchersalesinvoicedetails_exchange_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherSalesItemsForeign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('uqc', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_items', to='accounting.vouchersalesinvoicedetails')),
            ],
            options={
                'verbose_name': 'Voucher Sales Item Foreign',
                'db_table': 'voucher_sales_items_foreign',
            },
        ),
    ]
