# Generated by Django on 2025-12-29

from django.db import migrations


def backfill_ledger_codes(apps, schema_editor):
    """
    Generate codes for existing ledgers that don't have one.
    
    This migration backfills the ledger_code field for all existing
    ledgers in the database based on their hierarchy position.
    """
    print("=" * 60)
    print("BACKFILLING LEDGER CODES")
    print("=" * 60)
    
    MasterLedger = apps.get_model('accounting', 'MasterLedger')
    
    # Get all ledgers without codes
    try:
        ledgers_without_code = MasterLedger.objects.filter(code__isnull=True)
        total_count = ledgers_without_code.count()
    except Exception as e:
        print(f"⚠️  Could not query ledgers: {e}")
        print("Skipping backfill - this is normal if no ledgers exist yet.")
        return
    
    if total_count == 0:
        print("✅ No ledgers need code backfilling. All done!")
        return
    
    print(f"🔄 Found {total_count} ledgers without codes")
    print("⚠️  Skipping automatic backfill in migration")
    print("   Run this command after migration to backfill:")
    print("   python manage.py shell")
    print("   >>> from accounting.models import MasterLedger")
    print("   >>> from accounting.utils import generate_ledger_code")
    print("   >>> for ledger in MasterLedger.objects.filter(code__isnull=True):")
    print("   >>>     ledger_data = {")
    print("   >>>         'name': ledger.name,")
    print("   >>>         'category': getattr(ledger, 'category', None),")
    print("   >>>         'group': getattr(ledger, 'group', None),")
    print("   >>>     }")
    print("   >>>     ledger.code = generate_ledger_code(ledger_data, ledger.tenant_id)")
    print("   >>>     ledger.save()")
    print("=" * 60)


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration - set all codes to NULL.
    
    This is used if we need to rollback the migration.
    """
    MasterLedger = apps.get_model('accounting', 'MasterLedger')
    
    import logging
    logger = logging.getLogger('accounting.migrations')
    
    count = MasterLedger.objects.filter(code__isnull=False).count()
    logger.info(f"🔄 Clearing codes for {count} ledgers...")
    
    MasterLedger.objects.all().update(code=None)
    
    logger.info(f"✅ Cleared all ledger codes")


class Migration(migrations.Migration):
    """
    Backfill ledger codes for existing ledgers.
    
    This migration generates codes for all existing ledgers that don't
    have one, based on their hierarchy position.
    """

    dependencies = [
        ('accounting', '0011_add_ledger_code'),
    ]

    operations = [
        migrations.RunPython(backfill_ledger_codes, reverse_backfill),
    ]
