# Generated by Django 5.0.14 on 2026-01-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_vouchersalesitemsforeign'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherContra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=100)),
                ('from_account', models.CharField(help_text='Source Ledger (Credit)', max_length=255)),
                ('to_account', models.CharField(help_text='Destination Ledger (Debit)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('narration', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voucher_contra',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=100)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('narration', models.TextField(blank=True, null=True)),
                ('entries', models.JSONField(default=list, help_text='List of journal entries')),
            ],
            options={
                'db_table': 'voucher_journal',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
