# Generated by Django 5.0.14 on 2026-01-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_vouchercontra_voucherjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPurchaseSupplierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('supplier_invoice_no', models.CharField(max_length=100)),
                ('purchase_voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('grn_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_from', models.TextField(blank=True, null=True)),
                ('ship_from', models.TextField(blank=True, null=True)),
                ('input_type', models.CharField(default='Intrastate', max_length=50)),
                ('invoice_in_foreign_currency', models.CharField(default='No', max_length=10)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='purchase_documents/')),
            ],
            options={
                'db_table': 'voucher_purchase_supplier_details',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherPurchaseDueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tds_gst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tds_it', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('posting_note', models.TextField(blank=True, null=True)),
                ('terms', models.CharField(blank=True, max_length=255, null=True)),
                ('advance_references', models.JSONField(blank=True, default=list, null=True)),
                ('supplier_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due_details', to='accounting.voucherpurchasesupplierdetails')),
            ],
            options={
                'db_table': 'voucher_purchase_due_details',
            },
        ),
        migrations.CreateModel(
            name='VoucherPurchaseSupplyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('purchase_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_ledger', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('supplier_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_details', to='accounting.voucherpurchasesupplierdetails')),
            ],
            options={
                'db_table': 'voucher_purchase_supply_details',
            },
        ),
        migrations.CreateModel(
            name='VoucherPurchaseTransitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mode', models.CharField(default='Road', max_length=50)),
                ('received_in', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('receipt_time', models.TimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('self_third_party', models.CharField(blank=True, max_length=100, null=True)),
                ('transporter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('lr_gr_consignment', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='purchase_transit_documents/')),
                ('extra_details', models.JSONField(blank=True, default=dict)),
                ('supplier_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_details', to='accounting.voucherpurchasesupplierdetails')),
            ],
            options={
                'db_table': 'voucher_purchase_transit_details',
            },
        ),
    ]
