# Generated by Django 5.0.14 on 2026-01-02 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_add_questions_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_group_1_1', models.CharField(blank=True, db_column='sub_group_1_1', help_text='Sub-group 1 level 1 from hierarchy', max_length=255, null=True)),
                ('sub_group_1_2', models.CharField(blank=True, db_column='sub_group_1_2', help_text='Sub-group 1 level 2 (question code)', max_length=50, null=True)),
                ('question', models.TextField(blank=True, help_text='The question text', null=True)),
                ('condition_rule', models.CharField(blank=True, help_text='Condition rules for displaying the question', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_code', models.CharField(blank=True, help_text='Denormalized Ledger Code', max_length=50, null=True)),
                ('question_code', models.CharField(blank=True, help_text='Copy of question sub_group_1_2', max_length=50, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers_rel', to='accounting.masterledger')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounting.question')),
            ],
            options={
                'db_table': 'answers',
                'unique_together': {('ledger', 'question')},
            },
        ),
    ]
