# Generated by Django 5.0.14 on 2026-01-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_voucherpurchasesupplierdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPurchaseSupplyForeignDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('purchase_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('supplier_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_foreign_details', to='accounting.voucherpurchasesupplierdetails')),
            ],
            options={
                'db_table': 'voucher_purchase_supply_foreign_details',
            },
        ),
        migrations.CreateModel(
            name='VoucherPurchaseSupplyINRDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('purchase_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_ledger', models.CharField(blank=True, max_length=255, null=True)),
                ('items', models.JSONField(default=list)),
                ('supplier_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_inr_details', to='accounting.voucherpurchasesupplierdetails')),
            ],
            options={
                'db_table': 'voucher_purchase_supply_inr_details',
            },
        ),
        migrations.DeleteModel(
            name='VoucherPurchaseSupplyDetails',
        ),
    ]
