# Generated by Django 5.0.14 on 2026-01-05 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_masterhierarchyraw_question_masterchartofaccounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterHierarchyRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major_group_1', models.TextField(blank=True, null=True)),
                ('group_1', models.TextField(blank=True, null=True)),
                ('sub_group_1_1', models.TextField(blank=True, null=True)),
                ('sub_group_2_1', models.TextField(blank=True, null=True)),
                ('sub_group_3_1', models.TextField(blank=True, null=True)),
                ('ledger_1', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_hierarchy_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_business', models.CharField(max_length=255)),
                ('financial_reporting', models.CharField(max_length=255)),
                ('major_group', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('sub_group_1', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_group_2', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_group_3', models.CharField(blank=True, max_length=255, null=True)),
                ('ledger_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ledger_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('level_depth', models.IntegerField(default=1)),
                ('import_version', models.CharField(default='1.0', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('is_leaf', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Master Chart of Accounts',
                'db_table': 'master_chart_of_accounts',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='masterledger',
            name='ledger_code',
        ),
        migrations.AddField(
            model_name='masterledger',
            name='additional_data',
            field=models.JSONField(blank=True, help_text='Stores answers to dynamic questions (e.g., opening balance, GSTIN, credit limit)', null=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='code',
            field=models.CharField(blank=True, db_column='ledger_code', help_text='Auto-generated code based on hierarchy position', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='ledger_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='parent_ledger_id',
            field=models.IntegerField(blank=True, help_text='ID of parent custom ledger for nested structure', null=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='sub_group_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='sub_group_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='sub_group_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='extended_data',
            field=models.JSONField(blank=True, help_text='Group-specific fields (e.g., cashLocation, loanAccountNumber)', null=True),
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterledgergroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterledgergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastervoucherconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastervoucherconfig',
            name='purchase_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mastervoucherconfig',
            name='purchase_suffix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mastervoucherconfig',
            name='sales_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mastervoucherconfig',
            name='sales_suffix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mastervoucherconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='TenantLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('custom_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('master_ledger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounting.masterchartofaccounts')),
            ],
            options={
                'db_table': 'tenant_ledgers',
                'unique_together': {('tenant_id', 'master_ledger')},
            },
        ),
        migrations.DeleteModel(
            name='HierarchyQuestionMapping',
        ),
        migrations.DeleteModel(
            name='MasterQuestion',
        ),
    ]
