# Generated by Django 5.2.9 on 2026-01-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_masterhierarchyraw_masterchartofaccounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('voucher_date', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_from_address', models.TextField(blank=True, null=True)),
                ('ship_from_address', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_person', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('msme_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('ledger_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('ledger_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('ledger_dr_cr', models.CharField(blank=True, db_column='ledger_amount_dr_cr', max_length=10, null=True)),
                ('ledger_narration', models.TextField(blank=True, null=True)),
                ('ledger_description', models.TextField(blank=True, db_column='description_of_ledger', null=True)),
                ('tax_payment_type', models.CharField(blank=True, db_column='type_of_tax_payment', max_length=100, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_description', models.TextField(blank=True, db_column='item_description', null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('uom', models.CharField(blank=True, db_column='quantity_uom', max_length=50, null=True)),
                ('item_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_pct', models.CharField(blank=True, db_column='disc_pct', max_length=50, null=True)),
                ('item_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('marks', models.CharField(blank=True, max_length=255, null=True)),
                ('num_packages', models.CharField(blank=True, db_column='no_of_packages', max_length=50, null=True)),
                ('freight_charges', models.CharField(blank=True, max_length=50, null=True)),
                ('hsn_sac', models.CharField(blank=True, db_column='hsn_sac_details', max_length=20, null=True)),
                ('gst_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('igst_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('sgst_amount', models.CharField(blank=True, db_column='sgst_utgst_amount', max_length=50, null=True)),
                ('cess_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('cess_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('state_cess_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('state_cess_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('reverse_charge', models.CharField(blank=True, db_column='applicable_for_reverse_charge', max_length=10, null=True)),
                ('taxable_value', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_value', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_fields', models.JSONField(blank=True, help_text='Stores the remaining 60+ fields dynamically', null=True)),
            ],
            options={
                'db_table': 'extracted_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
