# Generated by Django 5.0.14 on 2026-01-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_transactionfile_voucherconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amounttransaction',
            name='name',
            field=models.CharField(blank=True, help_text="Ledger name (e.g., 'bank2', 'Cash', 'HDFC Bank')", max_length=255, null=True),
        ),
    ]
