# Generated by Django 6.0 on 2026-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_amounttransaction_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amounttransaction',
            old_name='name',
            new_name='ledger_name',
        ),
        migrations.AddField(
            model_name='amounttransaction',
            name='code',
            field=models.CharField(blank=True, help_text='Ledger code from master_ledgers table', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='amounttransaction',
            name='sub_group_1',
            field=models.CharField(blank=True, help_text="Sub group 1 from ledger (e.g., 'Current Assets')", max_length=255, null=True),
        ),
    ]
