# Generated by Django 5.0.14 on 2026-01-11 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_rename_name_amounttransaction_ledger_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptVoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'receipt_voucher_types',
                'ordering': ['display_order', 'name'],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SalesVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(help_text='Must be today or past date, no future dates allowed')),
                ('sales_invoice_number', models.CharField(help_text='Auto-generated, sequential, read-only', max_length=50)),
                ('bill_to_address', models.TextField(help_text='Auto-fetched, read-only')),
                ('bill_to_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('bill_to_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_to_state', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_to_country', models.CharField(default='India', max_length=100)),
                ('ship_to_address', models.TextField(help_text='Auto-fetched, editable, does not update customer master')),
                ('ship_to_state', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_country', models.CharField(default='India', max_length=100)),
                ('tax_type', models.CharField(choices=[('within_state', 'Within State'), ('other_state', 'Other State'), ('export', 'Export')], help_text='Auto-determined: Within State if User State = Bill To State, Other State if different states in India, Export if Bill To Country != India', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('current_step', models.IntegerField(default=1, help_text='Track which tab user is on (1-5)')),
                ('total_taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_details', models.JSONField(blank=True, help_text='Payment Details tab data', null=True)),
                ('dispatch_details', models.JSONField(blank=True, help_text='Dispatch Details tab data', null=True)),
                ('einvoice_details', models.JSONField(blank=True, help_text='E-Invoice & E-way Bill Details tab data', null=True)),
                ('customer', models.ForeignKey(help_text='Customer from Customer Module', on_delete=django.db.models.deletion.PROTECT, related_name='sales_vouchers', to='accounting.masterledger')),
                ('voucher_type', models.ForeignKey(help_text='From master list of Receipt Voucher Types', on_delete=django.db.models.deletion.PROTECT, to='accounting.receiptvouchertype')),
            ],
            options={
                'db_table': 'sales_vouchers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesVoucherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(help_text='jpg, jpeg, or pdf only', max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sales_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounting.salesvoucher')),
            ],
            options={
                'db_table': 'sales_voucher_documents',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_number', models.IntegerField(default=1)),
                ('sales_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.salesvoucher')),
            ],
            options={
                'db_table': 'sales_voucher_items',
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='salesvoucher',
            index=models.Index(fields=['tenant_id', 'date'], name='sales_vouch_tenant__180753_idx'),
        ),
        migrations.AddIndex(
            model_name='salesvoucher',
            index=models.Index(fields=['sales_invoice_number'], name='sales_vouch_sales_i_a4c9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='salesvoucher',
            index=models.Index(fields=['customer', 'tenant_id'], name='sales_vouch_custome_c9319a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesvoucher',
            unique_together={('tenant_id', 'sales_invoice_number')},
        ),
        migrations.AddIndex(
            model_name='salesvoucherdocument',
            index=models.Index(fields=['sales_voucher', 'tenant_id'], name='sales_vouch_sales_v_5e1e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesvoucheritem',
            index=models.Index(fields=['sales_voucher', 'tenant_id'], name='sales_vouch_sales_v_3a0ff1_idx'),
        ),
    ]
