# Generated by Django 5.0.14 on 2026-01-11 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_receiptvouchertype_salesvoucher_salesvoucherdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('invoice_number', models.CharField(help_text='Auto-generated, sequential', max_length=50)),
                ('invoice_date', models.DateField(help_text='Must be today or past date')),
                ('bill_to_address', models.TextField(help_text='Auto-fetched from customer')),
                ('bill_to_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('bill_to_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_to_state', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_to_country', models.CharField(default='India', max_length=100)),
                ('ship_to_address', models.TextField(help_text='Auto-fetched but editable')),
                ('ship_to_state', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_country', models.CharField(default='India', max_length=100)),
                ('tax_type', models.CharField(choices=[('within_state', 'Within State'), ('other_state', 'Other State'), ('export', 'Export')], help_text='Auto-determined from addresses', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('current_step', models.IntegerField(default=1, help_text='Current workflow step (1-5)')),
                ('customer', models.ForeignKey(help_text='Customer from ledgers', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.masterledger')),
                ('voucher_type', models.ForeignKey(help_text='Sales voucher type', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='accounting.receiptvouchertype')),
            ],
            options={
                'db_table': 'sales_invoices',
                'ordering': ['-invoice_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'invoice_date'], name='sales_invoi_tenant__62aed4_idx'), models.Index(fields=['customer', 'tenant_id'], name='sales_invoi_custome_aa5d4a_idx'), models.Index(fields=['voucher_type'], name='sales_invoi_voucher_e4d47a_idx')],
                'unique_together': {('tenant_id', 'invoice_number')},
            },
        ),
    ]
