# Generated by Django 6.0 on 2026-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_voucher_dummy_force'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='dummy_force',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('contra', 'Contra'), ('journal', 'Journal'), ('expenses', 'Expenses')], max_length=20),
        ),
    ]
