# Generated by Django 5.0.14 on 2026-01-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_voucher_dummy_force'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='voucher',
                    name='dummy_force',
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
            database_operations=[],  # Skip DB operation - column already exists from 0022
        ),
        migrations.AlterField(
            model_name='transactionfile',
            name='tenant_id',
            field=models.CharField(max_length=36),
        ),
    ]
