# Generated by Antigravity to fix conflicting migrations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_voucher_dummy_force'),
    ]

    operations = [
        # Handle dummy_force which exists in DB from 0022 but not in state for Voucher
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='voucher',
                    name='dummy_force',
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
            database_operations=[],  # Skip DB operation - column already exists from 0022
        ),
        # Ensure correct tenant_id type (CharField)
        migrations.AlterField(
            model_name='transactionfile',
            name='tenant_id',
            field=models.CharField(max_length=36),
        ),
        # Ensure correct voucher types (matching models.py, excluding 'expenses' if that was the conflict)
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(
                choices=[
                    ('sales', 'Sales'), 
                    ('purchase', 'Purchase'), 
                    ('payment', 'Payment'), 
                    ('receipt', 'Receipt'), 
                    ('contra', 'Contra'), 
                    ('journal', 'Journal')
                ], 
                max_length=20
            ),
        ),
    ]
