# Generated by Django 6.0 on 2026-01-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_voucher_dummy_force_alter_voucher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('contra', 'Contra'), ('journal', 'Journal')], max_length=20),
        ),
    ]
