# Generated by Django 5.0.14 on 2026-01-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_voucher_dummy_force_alter_transactionfile_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfile',
            name='tenant_id',
            field=models.BigIntegerField(),
        ),
    ]
