# Generated by Django 5.0.14 on 2026-01-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_add_separate_voucher_master_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastervouchersales',
            name='update_customer_master',
            field=models.BooleanField(default=False, help_text='Update customer master'),
        ),
    ]
