# Generated by Django 5.2.9 on 2026-01-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_mastervouchersales_update_customer_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('service_code', models.CharField(help_text='Unique service code', max_length=50, unique=True)),
                ('service_name', models.CharField(help_text='Service name', max_length=255)),
                ('service_group', models.CharField(help_text='Service group/category', max_length=100)),
                ('sac_code', models.CharField(help_text='Service Accounting Code (SAC)', max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='GST rate percentage', max_digits=5)),
                ('uom', models.CharField(blank=True, help_text='Unit of Measurement', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Service description', null=True)),
                ('expense_ledger', models.CharField(help_text='Expense ledger for accounting', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Service status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_code'], name='services_service_826d98_idx'), models.Index(fields=['service_group'], name='services_service_cace97_idx'), models.Index(fields=['is_active'], name='services_is_acti_b1f5d3_idx'), models.Index(fields=['tenant_id'], name='services_tenant__ea97fb_idx')],
                'unique_together': {('service_code', 'tenant_id')},
            },
        ),
    ]
