# Generated by Django 5.0.14 on 2026-01-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, help_text='Tenant ID for multi-tenancy', max_length=36, null=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_code'], name='service_lis_service_43ab40_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_group'], name='service_lis_service_8ffa00_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='service_lis_is_acti_da762e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='service_lis_created_fc7c06_idx'),
        ),
        migrations.AlterModelTable(
            name='service',
            table='service_list',
        ),
    ]
