# Generated by Django 5.0.14 on 2026-01-19 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_category',
                'unique_together': {('tenant_id', 'category_name')},
            },
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_days', models.IntegerField(default=0)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_master',
                'indexes': [models.Index(fields=['tenant_id', 'customer_code'], name='customer_ma_tenant__b35538_idx'), models.Index(fields=['tenant_id', 'is_deleted'], name='customer_ma_tenant__22d35a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerMastersSalesQuotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('series_name', models.CharField(max_length=100)),
                ('customer_category', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(default='SQ/', max_length=20)),
                ('suffix', models.CharField(default='/24-25', max_length=20)),
                ('required_digits', models.IntegerField(default=4)),
                ('current_number', models.IntegerField(default=0)),
                ('auto_year', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_masters_salesquotation',
                'indexes': [models.Index(fields=['tenant_id', 'is_deleted'], name='customer_ma_tenant__38822d_idx'), models.Index(fields=['tenant_id', 'customer_category'], name='customer_ma_tenant__227ff0_idx')],
                'unique_together': {('tenant_id', 'series_name')},
            },
        ),
        migrations.CreateModel(
            name='CustomerSalesOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('customer_id', models.IntegerField(db_index=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('quotation_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('po_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_sales_order',
                'indexes': [models.Index(fields=['tenant_id', 'customer_id'], name='customer_sa_tenant__f5e3e8_idx'), models.Index(fields=['order_date'], name='customer_sa_order_d_e9644e_idx'), models.Index(fields=['status'], name='customer_sa_status_ebc1e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerSalesQuotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('customer_id', models.IntegerField(db_index=True)),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('quotation_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('converted', 'Converted to Order')], default='draft', max_length=20)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_sales_quotation',
                'indexes': [models.Index(fields=['tenant_id', 'customer_id'], name='customer_sa_tenant__6d9840_idx'), models.Index(fields=['quotation_date'], name='customer_sa_quotati_b139f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('customer_id', models.IntegerField(db_index=True)),
                ('transaction_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=20)),
                ('transaction_number', models.CharField(max_length=50)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_transaction',
                'indexes': [models.Index(fields=['tenant_id', 'customer_id'], name='customer_tr_tenant__2b4a8c_idx'), models.Index(fields=['transaction_date'], name='customer_tr_transac_014b14_idx')],
            },
        ),
    ]
