# Generated by Django 5.0.14 on 2026-01-19 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMasterCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_code', models.CharField(max_length=50)),
                ('customer_category', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_also_vendor', models.BooleanField(default=False)),
                ('gst_details', models.JSONField(blank=True, help_text='Stores GST registration details and branch information', null=True)),
                ('products_services', models.JSONField(blank=True, help_text='Stores product/service mappings', null=True)),
                ('msme_no', models.CharField(blank=True, max_length=50, null=True)),
                ('fssai_no', models.CharField(blank=True, max_length=50, null=True)),
                ('iec_code', models.CharField(blank=True, max_length=50, null=True)),
                ('eou_status', models.CharField(blank=True, max_length=100, null=True)),
                ('tcs_section', models.CharField(blank=True, max_length=50, null=True)),
                ('tcs_enabled', models.BooleanField(default=False)),
                ('tds_section', models.CharField(blank=True, max_length=50, null=True)),
                ('tds_enabled', models.BooleanField(default=False)),
                ('banking_info', models.JSONField(blank=True, help_text='Stores bank account details', null=True)),
                ('credit_period', models.IntegerField(blank=True, help_text='Credit period in days', null=True)),
                ('credit_terms', models.TextField(blank=True, null=True)),
                ('penalty_terms', models.TextField(blank=True, null=True)),
                ('delivery_terms', models.TextField(blank=True, null=True)),
                ('warranty_details', models.TextField(blank=True, null=True)),
                ('force_majeure', models.TextField(blank=True, null=True)),
                ('dispute_terms', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_master_customer',
                'indexes': [models.Index(fields=['tenant_id', 'customer_code'], name='customer_ma_tenant__8eff02_idx'), models.Index(fields=['tenant_id', 'is_deleted'], name='customer_ma_tenant__2930ca_idx'), models.Index(fields=['customer_category'], name='customer_ma_custome_08554c_idx')],
                'unique_together': {('tenant_id', 'customer_code')},
            },
        ),
    ]
