# Generated by Django manual migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0002_customermastercustomer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customermastercustomer',
            table='customer_master_customer_basicdetail',
        ),
    ]
