# Generated by Django manual migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0003_rename_customer_table'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='CustomerCategory',
        # ),
        migrations.CreateModel(
            name='CustomerMasterCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('category', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_master_category',
            },
        ),
        migrations.AddIndex(
            model_name='customermastercategory',
            index=models.Index(fields=['tenant_id', 'is_active'], name='customer_ma_tenant__0d3460_idx'),
        ),
        migrations.AddIndex(
            model_name='customermastercategory',
            index=models.Index(fields=['category'], name='customer_ma_categor_872718_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customermastercategory',
            unique_together={('tenant_id', 'category', 'group', 'subgroup')},
        ),
    ]
