# Generated by Django 5.0.14 on 2026-01-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0004_replace_category_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCategory',
        ),
        migrations.RenameIndex(
            model_name='customermastercategory',
            new_name='customer_ma_tenant__ba3445_idx',
            old_name='customer_ma_tenant__0d3460_idx',
        ),
        migrations.RenameIndex(
            model_name='customermastercategory',
            new_name='customer_ma_categor_4b1a92_idx',
            old_name='customer_ma_categor_872718_idx',
        ),
        migrations.RenameIndex(
            model_name='customermastercustomer',
            new_name='customer_ma_tenant__5dd9a2_idx',
            old_name='customer_ma_tenant__8eff02_idx',
        ),
        migrations.RenameIndex(
            model_name='customermastercustomer',
            new_name='customer_ma_tenant__da1f26_idx',
            old_name='customer_ma_tenant__2930ca_idx',
        ),
        migrations.RenameIndex(
            model_name='customermastercustomer',
            new_name='customer_ma_custome_49e2a1_idx',
            old_name='customer_ma_custome_08554c_idx',
        ),
    ]
