# Generated by Django 5.0.14 on 2026-01-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0005_delete_customercategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermastercustomer',
            name='customer_category',
            field=models.ForeignKey(blank=True, db_column='customer_category', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customerportal.customermastercategory'),
        ),
    ]
