# Generated by Django 5.0.14 on 2026-01-19 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0006_alter_customermastercustomer_customer_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMasterCustomerProductService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_basic_detail', models.ForeignKey(db_column='customer_basic_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_services', to='customerportal.customermastercustomer')),
            ],
            options={
                'db_table': 'customer_master_customer_productservice',
                'indexes': [models.Index(fields=['tenant_id'], name='customer_ma_tenant__76e131_idx'), models.Index(fields=['item_code'], name='customer_ma_item_co_0c8927_idx')],
            },
        ),
    ]
