# Generated by Django 5.0.14 on 2026-01-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0007_customermastercustomerproductservice'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customermastercustomerproductservice',
            name='customer_ma_tenant__76e131_idx',
        ),
        migrations.RemoveIndex(
            model_name='customermastercustomerproductservice',
            name='customer_ma_item_co_0c8927_idx',
        ),
        migrations.RemoveField(
            model_name='customermastercustomerproductservice',
            name='is_active',
        ),
        migrations.AddIndex(
            model_name='customermastercustomerproductservice',
            index=models.Index(fields=['tenant_id', 'item_code'], name='customer_ma_tenant__10f7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='customermastercustomerproductservice',
            index=models.Index(fields=['customer_basic_detail'], name='customer_ma_custome_fe8526_idx'),
        ),
    ]
