# Generated by Django 5.0.14 on 2026-01-19 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0008_remove_customermastercustomerproductservice_customer_ma_tenant__76e131_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMasterCustomerTermsCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('credit_period', models.IntegerField(blank=True, help_text='Credit period in days', null=True)),
                ('credit_terms', models.TextField(blank=True, null=True)),
                ('penalty_terms', models.TextField(blank=True, null=True)),
                ('delivery_terms', models.TextField(blank=True, null=True)),
                ('warranty_details', models.TextField(blank=True, null=True)),
                ('force_majeure', models.TextField(blank=True, null=True)),
                ('dispute_terms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_basic_detail', models.OneToOneField(db_column='customer_basic_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='customerportal.customermastercustomer')),
            ],
            options={
                'db_table': 'customer_master_customer_termscondition',
                'indexes': [models.Index(fields=['tenant_id'], name='customer_ma_tenant__f49779_idx'), models.Index(fields=['customer_basic_detail'], name='customer_ma_custome_85223c_idx')],
            },
        ),
    ]
