# Generated by Django 5.0.14 on 2026-01-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0009_customermastercustomertermscondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermastercustomer',
            name='credit_period',
            field=models.CharField(blank=True, help_text='Credit period field', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customermastercustomertermscondition',
            name='credit_period',
            field=models.CharField(blank=True, help_text='Credit period field', max_length=50, null=True),
        ),
    ]
