# Generated by Django 5.0.14 on 2026-01-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0010_alter_customermastercustomer_credit_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMasterLongTermContractBasicDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('contract_number', models.CharField(max_length=50)),
                ('customer_id', models.IntegerField(db_index=True, help_text='Reference to customer')),
                ('customer_name', models.CharField(help_text='Customer name for display', max_length=255)),
                ('branch_id', models.IntegerField(blank=True, help_text='Reference to branch', null=True)),
                ('contract_type', models.CharField(choices=[('Rate Contract', 'Rate Contract'), ('Service Contract', 'Service Contract'), ('AMC', 'AMC')], max_length=50)),
                ('contract_validity_from', models.DateField()),
                ('contract_validity_to', models.DateField()),
                ('contract_document', models.CharField(blank=True, help_text='File path to uploaded contract document', max_length=500, null=True)),
                ('automate_billing', models.BooleanField(default=False)),
                ('bill_start_date', models.DateField(blank=True, null=True)),
                ('billing_frequency', models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Yearly', 'Yearly')], max_length=20, null=True)),
                ('voucher_name', models.CharField(blank=True, help_text='Voucher type for automated billing', max_length=100, null=True)),
                ('bill_period_from', models.DateField(blank=True, null=True)),
                ('bill_period_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_master_longtermcontracts_basicdetails',
                'indexes': [models.Index(fields=['tenant_id', 'contract_number'], name='customer_ma_tenant__3fc2c9_idx'), models.Index(fields=['tenant_id', 'customer_id'], name='customer_ma_tenant__19072f_idx'), models.Index(fields=['tenant_id', 'is_deleted'], name='customer_ma_tenant__47ad93_idx'), models.Index(fields=['contract_validity_from', 'contract_validity_to'], name='customer_ma_contrac_0cb879_idx')],
                'unique_together': {('tenant_id', 'contract_number')},
            },
        ),
        migrations.CreateModel(
            name='CustomerMasterLongTermContractProductService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('item_code', models.CharField(help_text='Our item code', max_length=50)),
                ('item_name', models.CharField(help_text='Our item name', max_length=200)),
                ('customer_item_name', models.CharField(blank=True, help_text="Customer's item name", max_length=200, null=True)),
                ('qty_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity', max_digits=15, null=True)),
                ('qty_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum quantity', max_digits=15, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price', max_digits=15, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price', max_digits=15, null=True)),
                ('acceptable_price_deviation', models.CharField(blank=True, help_text='e.g., ±5%', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_basic_detail', models.ForeignKey(db_column='contract_basic_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='products_services', to='customerportal.customermasterlongtermcontractbasicdetail')),
            ],
            options={
                'db_table': 'customer_master_longtermcontracts_productservices',
                'indexes': [models.Index(fields=['tenant_id', 'item_code'], name='customer_ma_tenant__ea7198_idx'), models.Index(fields=['contract_basic_detail'], name='customer_ma_contrac_c2db81_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerMasterLongTermContractTermsCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('penalty_terms', models.TextField(blank=True, null=True)),
                ('force_majeure', models.TextField(blank=True, null=True)),
                ('termination_clause', models.TextField(blank=True, null=True)),
                ('dispute_terms', models.TextField(blank=True, help_text='Dispute & Redressal Terms', null=True)),
                ('others', models.TextField(blank=True, help_text='Other terms', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_basic_detail', models.OneToOneField(db_column='contract_basic_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='customerportal.customermasterlongtermcontractbasicdetail')),
            ],
            options={
                'db_table': 'customer_master_longtermcontracts_termscondition',
                'indexes': [models.Index(fields=['tenant_id'], name='customer_ma_tenant__de94b9_idx'), models.Index(fields=['contract_basic_detail'], name='customer_ma_contrac_d5232b_idx')],
            },
        ),
    ]
