# Generated by Django 5.0.14 on 2026-01-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0011_customermasterlongtermcontractbasicdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermastercustomerproductservice',
            name='customer_uom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermastercustomerproductservice',
            name='uom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
