# Generated by Django 5.0.14 on 2026-01-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0013_create_customer_separate_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermastercustomerproductservice',
            name='customer_basic_detail',
            field=models.ForeignKey(db_column='customer_basic_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_services', to='customerportal.customermastercustomerbasicdetails'),
        ),
        migrations.AlterField(
            model_name='customermastercustomertermscondition',
            name='customer_basic_detail',
            field=models.OneToOneField(db_column='customer_basic_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='customerportal.customermastercustomerbasicdetails'),
        ),
        migrations.AlterField(
            model_name='customermastercustomerbanking',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank Account Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customermastercustomerbanking',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customermastercustomerbanking',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC Code', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customermastercustomerbasicdetails',
            name='customer_category',
            field=models.ForeignKey(blank=True, db_column='customer_category_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customerportal.customermastercategory'),
        ),
        migrations.DeleteModel(
            name='CustomerMasterCustomer',
        ),
    ]
