# Generated by Django 5.0.14 on 2026-01-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0014_alter_customermastercustomerproductservice_customer_basic_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransactionSalesOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('so_series', models.CharField(blank=True, max_length=100, null=True)),
                ('so_number', models.CharField(max_length=50, unique=True)),
                ('so_date', models.DateField()),
                ('customer_po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('quotation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('quotation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('deliver_at', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('credit_period', models.CharField(blank=True, max_length=50, null=True)),
                ('salesperson_in_charge', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_value_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_transaction_salesorder',
                'indexes': [models.Index(fields=['tenant_id', 'so_number'], name='customer_tr_tenant__e6dac6_idx'), models.Index(fields=['so_date'], name='customer_tr_so_date_f1de9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesOrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_order', models.ForeignKey(db_column='sales_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customerportal.customertransactionsalesorder')),
            ],
            options={
                'db_table': 'customer_transaction_salesorder_item',
            },
        ),
    ]
