# Generated by Django 5.0.14 on 2026-01-20 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0015_customertransactionsalesorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransactionsalesorderitem',
            name='sales_order',
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesQuotationGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('quote_number', models.CharField(max_length=50, unique=True)),
                ('customer_category', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_transaction_salesquotation_general',
                'indexes': [models.Index(fields=['tenant_id', 'quote_number'], name='customer_tr_tenant__beaa68_idx'), models.Index(fields=['effective_from'], name='customer_tr_effecti_13f1a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesQuotationGeneralItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('best_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('general_quote', models.ForeignKey(db_column='general_quote_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customerportal.customertransactionsalesquotationgeneral')),
            ],
            options={
                'db_table': 'customer_transaction_salesquotation_general_item',
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesQuotationSpecific',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('quote_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('validity_from', models.DateField(blank=True, null=True)),
                ('validity_to', models.DateField(blank=True, null=True)),
                ('tentative_delivery_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_transaction_salesquotation_specific',
                'indexes': [models.Index(fields=['tenant_id', 'quote_number'], name='customer_tr_tenant__5dec9c_idx'), models.Index(fields=['validity_from'], name='customer_tr_validit_8437dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesQuotationSpecificItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('negotiated_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('specific_quote', models.ForeignKey(db_column='specific_quote_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customerportal.customertransactionsalesquotationspecific')),
            ],
            options={
                'db_table': 'customer_transaction_salesquotation_specific_item',
            },
        ),
        migrations.DeleteModel(
            name='CustomerTransactionSalesOrder',
        ),
        migrations.DeleteModel(
            name='CustomerTransactionSalesOrderItem',
        ),
    ]
