# Generated by Django 5.0.14 on 2026-01-20 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0016_remove_customertransactionsalesorderitem_sales_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransactionSalesOrderBasicDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('so_series_name', models.CharField(blank=True, help_text='SO Series Name', max_length=100, null=True)),
                ('so_number', models.CharField(help_text='Sales Order Number (auto-generated)', max_length=50)),
                ('date', models.DateField(help_text='Sales Order Date')),
                ('customer_po_number', models.CharField(blank=True, help_text='Customer PO Number', max_length=100, null=True)),
                ('customer_name', models.CharField(help_text='Customer Name', max_length=255)),
                ('branch', models.CharField(blank=True, help_text='Branch', max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Address', null=True)),
                ('email', models.EmailField(blank=True, help_text='Email Address', max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, help_text='Contact Number', max_length=20, null=True)),
                ('quotation_type', models.CharField(blank=True, help_text='Type: Sales Quotation or Contract', max_length=50, null=True)),
                ('quotation_number', models.CharField(blank=True, help_text='Sales Quotation # / Contract #', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_transaction_salesorder_basicdetails',
                'indexes': [models.Index(fields=['tenant_id'], name='customer_tr_tenant__2c296b_idx'), models.Index(fields=['customer_name'], name='customer_tr_custome_5b9b93_idx'), models.Index(fields=['date'], name='customer_tr_date_3be321_idx')],
                'unique_together': {('tenant_id', 'so_number')},
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesOrderDeliveryTerms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('deliver_at', models.CharField(blank=True, help_text='Delivery Address', max_length=500, null=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Delivery Date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_basic_detail', models.OneToOneField(db_column='so_basic_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_terms', to='customerportal.customertransactionsalesorderbasicdetails')),
            ],
            options={
                'db_table': 'customer_transaction_salesorder_deliveryterms',
                'indexes': [models.Index(fields=['tenant_id'], name='customer_tr_tenant__0f6456_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesOrderItemDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('item_code', models.CharField(blank=True, help_text='Item Code', max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, help_text='Item Name', max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity', max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, help_text='Taxable Value (Qty * Price)', max_digits=15)),
                ('gst', models.DecimalField(decimal_places=2, default=0, help_text='GST Amount', max_digits=15)),
                ('net_value', models.DecimalField(decimal_places=2, default=0, help_text='Net Value (Taxable + GST)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_basic_detail', models.ForeignKey(db_column='so_basic_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customerportal.customertransactionsalesorderbasicdetails')),
            ],
            options={
                'db_table': 'customer_transaction_salesorder_items',
                'indexes': [models.Index(fields=['tenant_id'], name='customer_tr_tenant__2f0cd7_idx'), models.Index(fields=['so_basic_detail'], name='customer_tr_so_basi_b71f7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesOrderPaymentTerms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('credit_period', models.CharField(blank=True, help_text='Credit Period', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_basic_detail', models.OneToOneField(db_column='so_basic_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='customerportal.customertransactionsalesorderbasicdetails')),
            ],
            options={
                'db_table': 'customer_transaction_salesorder_paymentterms',
                'indexes': [models.Index(fields=['tenant_id'], name='customer_tr_tenant__e68787_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesOrderSalesperson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID / Agent ID', max_length=50, null=True)),
                ('employee_name', models.CharField(blank=True, help_text='Employee Name / Agent Name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_basic_detail', models.OneToOneField(db_column='so_basic_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='salesperson', to='customerportal.customertransactionsalesorderbasicdetails')),
            ],
            options={
                'db_table': 'customer_transaction_salesorder_salesperson',
                'indexes': [models.Index(fields=['tenant_id'], name='customer_tr_tenant__9f815f_idx')],
            },
        ),
    ]
