# Generated by Django 5.0.14 on 2026-01-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0018_add_salesperson_in_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransactionsalesordersalesperson',
            name='so_basic_detail',
        ),
        migrations.RemoveField(
            model_name='customertransactionsalesorderbasicdetails',
            name='quotation_number',
        ),
        migrations.RemoveField(
            model_name='customertransactionsalesorderbasicdetails',
            name='quotation_type',
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesOrderPaymentAndSalesperson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('credit_period', models.CharField(blank=True, help_text='Credit Period', max_length=100, null=True)),
                ('salesperson_in_charge', models.CharField(blank=True, help_text='Salesperson In Charge', max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID / Agent ID', max_length=50, null=True)),
                ('employee_name', models.CharField(blank=True, help_text='Employee Name / Agent Name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_basic_detail', models.OneToOneField(db_column='so_basic_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_and_salesperson', to='customerportal.customertransactionsalesorderbasicdetails')),
            ],
            options={
                'db_table': 'customer_transaction_salesorder_payment_salesperson',
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionSalesOrderQuotationDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('quotation_type', models.CharField(blank=True, help_text='Type: Sales Quotation or Contract', max_length=50, null=True)),
                ('quotation_number', models.CharField(blank=True, help_text='Sales Quotation # / Contract #', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_basic_detail', models.OneToOneField(db_column='so_basic_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='quotation_details', to='customerportal.customertransactionsalesorderbasicdetails')),
            ],
            options={
                'db_table': 'customer_transaction_salesorder_quotation_details',
            },
        ),
        migrations.DeleteModel(
            name='CustomerTransactionSalesOrderPaymentTerms',
        ),
        migrations.DeleteModel(
            name='CustomerTransactionSalesOrderSalesperson',
        ),
        migrations.AddIndex(
            model_name='customertransactionsalesorderpaymentandsalesperson',
            index=models.Index(fields=['tenant_id'], name='customer_tr_tenant__9ce95b_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransactionsalesorderquotationdetails',
            index=models.Index(fields=['tenant_id'], name='customer_tr_tenant__d1ffba_idx'),
        ),
    ]
