# Generated by Django 5.0.14 on 2025-12-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('reset', 'Password Reset')], db_index=True, max_length=20)),
                ('otp_hash', models.CharField(max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Record',
                'verbose_name_plural': 'OTP Records',
                'db_table': 'otp_records',
                'indexes': [models.Index(fields=['identifier', 'purpose'], name='otp_records_identif_afc2f0_idx')],
            },
        ),
    ]
