# Generated by Django 6.0 on 2025-12-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockgroup',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
