# Generated by Django 5.0.14 on 2026-01-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryoperationgrnitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationinterunititem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationjobworkitem',
            name='job_work',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationlocationchangeitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationnewgrnitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationoutwarditem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationproductionitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='inventoryoperationscrapitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='inventoryoperationconsumption',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationgrn',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationinterunit',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationjobwork',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationlocationchange',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationnewgrn',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationoutward',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationproduction',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoperationscrap',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='InventoryOperationConsumptionItem',
        ),
        migrations.DeleteModel(
            name='InventoryOperationGRNItem',
        ),
        migrations.DeleteModel(
            name='InventoryOperationInterUnitItem',
        ),
        migrations.DeleteModel(
            name='InventoryOperationJobWorkItem',
        ),
        migrations.DeleteModel(
            name='InventoryOperationLocationChangeItem',
        ),
        migrations.DeleteModel(
            name='InventoryOperationNewGRNItem',
        ),
        migrations.DeleteModel(
            name='InventoryOperationOutwardItem',
        ),
        migrations.DeleteModel(
            name='InventoryOperationProductionItem',
        ),
        migrations.DeleteModel(
            name='InventoryOperationScrapItem',
        ),
    ]
