# Generated by Django 5.0.14 on 2025-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockgroup_tenant_id_alter_stockitem_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('type', models.CharField(choices=[('Unit', 'Unit'), ('StockGroup', 'StockGroup'), ('StockItem', 'StockItem')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='unit',
        ),
        migrations.DeleteModel(
            name='StockGroup',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.CreateModel(
            name='StockGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventorymaster',),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventorymaster',),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventorymaster',),
        ),
    ]
