# Generated by Django 5.0.14 on 2026-01-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryoperationconsumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOperationDeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('issue_slip_no', models.CharField(max_length=100)),
                ('dispatch_address', models.TextField(blank=True, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_operation_deliverychallan',
            },
        ),
        migrations.CreateModel(
            name='InventoryOperationEWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('issue_slip_no', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('valid_till', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_operation_ewaybill',
            },
        ),
    ]
