# Generated by Django 5.0.14 on 2025-12-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymaster_remove_stockitem_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.CharField(blank=True, help_text='Parent group name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventory_stock_groups',
                'ordering': ['name'],
                'unique_together': {('name', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='InventoryStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(help_text='Stock group name', max_length=255)),
                ('unit', models.CharField(help_text='Unit name', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=3, default=0, help_text='Opening stock quantity', max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=3, default=0, help_text='Current stock quantity', max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Default rate/price', max_digits=15)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, help_text='GST percentage', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_stock_items',
                'ordering': ['name'],
                'unique_together': {('name', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(help_text='e.g., Kg, L, Pcs', max_length=20)),
            ],
            options={
                'db_table': 'inventory_units',
                'ordering': ['name'],
                'unique_together': {('name', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('stock_item', models.CharField(help_text='Stock item name', max_length=255)),
                ('transaction_type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('adjustment', 'Stock Adjustment')], max_length=20)),
                ('transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('narration', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.DeleteModel(
            name='InventoryMaster',
        ),
        migrations.DeleteModel(
            name='StockGroup',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', 'transaction_date'], name='stock_movem_stock_i_995aee_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['transaction_type', 'transaction_id'], name='stock_movem_transac_e9b728_idx'),
        ),
    ]
