# Generated by Django 6.0 on 2026-01-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorystockgroup_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('is_system', models.BooleanField(default=False, help_text='System-defined categories cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='InventoryStockGroup',
        ),
        migrations.DeleteModel(
            name='InventoryStockItem',
        ),
        migrations.DeleteModel(
            name='InventoryUnit',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='stock_movem_stock_i_995aee_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='stock_movem_transac_e9b728_idx',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.inventorycategory'),
        ),
        migrations.AddIndex(
            model_name='inventorycategory',
            index=models.Index(fields=['tenant_id', 'is_active'], name='inventory_c_tenant__eb3093_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycategory',
            index=models.Index(fields=['parent'], name='inventory_c_parent__90e9ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycategory',
            unique_together={('tenant_id', 'name', 'parent')},
        ),
    ]
