# Generated by Django 6.0 on 2026-01-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorycategory_delete_inventorystockgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Location name', max_length=255)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store'), ('godown', 'Godown'), ('factory', 'Factory'), ('office', 'Office'), ('other', 'Other')], help_text='Type of location', max_length=50)),
                ('address', models.TextField(help_text='Location address')),
                ('gstin', models.CharField(blank=True, help_text='GSTIN for this location (optional)', max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default location for transactions')),
            ],
            options={
                'db_table': 'inventory_locations',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='inventory_l_tenant__0744f6_idx'), models.Index(fields=['location_type'], name='inventory_l_locatio_5fbc5e_idx')],
                'unique_together': {('tenant_id', 'name')},
            },
        ),
    ]
