# Generated by Django 6.0 on 2026-01-12 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorylocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylocation',
            name='address',
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='address_line1',
            field=models.CharField(default='', help_text='Address Line 1 (Required)', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Address Line 2 (Optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='address_line3',
            field=models.CharField(blank=True, help_text='Address Line 3 (Optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='city',
            field=models.CharField(default='', help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='country',
            field=models.CharField(default='India', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='pincode',
            field=models.CharField(default='', help_text='Pincode/Zip Code', max_length=20),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='state',
            field=models.CharField(default='', help_text='State', max_length=100),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_code', models.CharField(help_text='Auto or Custom Item Code', max_length=50)),
                ('name', models.CharField(help_text='Item Name', max_length=255)),
                ('hsn_code', models.CharField(blank=True, help_text='HSN Code', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Description (Automatic from HSN logic placeholder)', null=True)),
                ('unit', models.CharField(choices=[('nos', 'Numbers'), ('kg', 'Kilograms'), ('gm', 'Grams'), ('m', 'Meters'), ('cm', 'Centimeters'), ('l', 'Liters'), ('ml', 'Milliliters'), ('box', 'Box'), ('pch', 'Pouch'), ('set', 'Set'), ('pcs', 'Pieces'), ('doz', 'Dozen'), ('bag', 'Bag'), ('bdl', 'Bundle'), ('can', 'Can'), ('btl', 'Bottle')], default='nos', help_text='Primary Unit', max_length=20)),
                ('has_multiple_units', models.BooleanField(default=False, help_text='Show multiple units')),
                ('alternative_unit', models.CharField(blank=True, choices=[('nos', 'Numbers'), ('kg', 'Kilograms'), ('gm', 'Grams'), ('m', 'Meters'), ('cm', 'Centimeters'), ('l', 'Liters'), ('ml', 'Milliliters'), ('box', 'Box'), ('pch', 'Pouch'), ('set', 'Set'), ('pcs', 'Pieces'), ('doz', 'Dozen'), ('bag', 'Bag'), ('bdl', 'Bundle'), ('can', 'Can'), ('btl', 'Bottle')], help_text='Alternative Unit', max_length=20, null=True)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, help_text='Factor to convert: 1 Alternative Unit = X Primary Unit (e.g., 1 Box = 200 Nos)', max_digits=10, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='GST Rate (%)', max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Rate per unit', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(help_text='Category from master', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory')),
                ('location', models.ForeignKey(blank=True, help_text='Default Location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorylocation')),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant_id', 'name'], name='inventory_i_tenant__36610f_idx'), models.Index(fields=['hsn_code'], name='inventory_i_hsn_cod_83c360_idx'), models.Index(fields=['category'], name='inventory_i_categor_9c3f50_idx')],
                'unique_together': {('tenant_id', 'item_code')},
            },
        ),
    ]
