# Generated by Django 5.0.14 on 2026-01-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventorylocation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHierarchy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, help_text='Main Category (e.g., RAW MATERIAL)', max_length=255, null=True)),
                ('group', models.CharField(blank=True, help_text='Group under category', max_length=255, null=True)),
                ('subgroup', models.CharField(blank=True, help_text='Subgroup under group', max_length=255, null=True)),
                ('code', models.CharField(blank=True, help_text='Hierarchy code', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_hierarchy',
                'ordering': ['category', 'group', 'subgroup'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='category',
            field=models.CharField(blank=True, help_text='Level 1: Category', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='group',
            field=models.CharField(blank=True, help_text='Level 2: Group', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='subgroup',
            field=models.CharField(blank=True, help_text='Level 3: Subgroup', max_length=255, null=True),
        ),
    ]
