# Generated by Django 6.0 on 2026-01-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventorylocation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='location_type',
            field=models.CharField(help_text='Type of location (predefined or custom)', max_length=50),
        ),
    ]
