# Generated by Django 5.0.14 on 2026-01-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryhierarchy_inventorycategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(help_text='Top-level category (e.g., RAW MATERIAL, Finished goods)', max_length=255)),
                ('group', models.CharField(blank=True, help_text='Group under category (optional)', max_length=255, null=True)),
                ('subgroup', models.CharField(blank=True, help_text='Subgroup under group (optional)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_master_category',
                'ordering': ['category', 'group', 'subgroup'],
            },
        ),
        migrations.DeleteModel(
            name='InventoryHierarchy',
        ),
        migrations.RemoveField(
            model_name='inventorycategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventorycategory',
            name='group',
        ),
        migrations.RemoveField(
            model_name='inventorycategory',
            name='subgroup',
        ),
        migrations.AddIndex(
            model_name='inventorymastercategory',
            index=models.Index(fields=['tenant_id', 'is_active'], name='inventory_m_tenant__29c59a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymastercategory',
            index=models.Index(fields=['category'], name='inventory_m_categor_cd5bfd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorymastercategory',
            unique_together={('tenant_id', 'category', 'group', 'subgroup')},
        ),
    ]
