# Generated by Django 5.0.14 on 2026-01-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorymastercategory_delete_inventoryhierarchy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.AlterUniqueTogether(
            name='inventorylocation',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='InventoryLocation',
        ),
    ]
