# Generated by Django 5.0.14 on 2026-01-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventorylocation_location_type'),
        ('inventory', '0011_remove_inventoryitem_category_and_more'),
    ]

    operations = [
    ]
