# Generated by helper script

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_merge_20260114_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.inventorystockgroup')),
            ],
            options={
                'db_table': 'inventory_stock_group',
            },
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_unit',
            },
        ),
        migrations.CreateModel(
            name='InventoryStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorystockgroup')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventoryunit')),
            ],
            options={
                'db_table': 'inventory_stock_item',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('voucher_type', models.CharField(max_length=50)),
                ('voucher_id', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10)),
                ('narraration', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventorystockitem')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
            },
        ),
    ]
