# Generated by Django 5.0.14 on 2026-01-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_restore_models_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Location name', max_length=255)),
                ('location_type', models.CharField(help_text='Type of location (predefined or custom)', max_length=50)),
                ('address_line1', models.CharField(default='', help_text='Address Line 1 (Required)', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Address Line 2 (Optional)', max_length=255, null=True)),
                ('address_line3', models.CharField(blank=True, help_text='Address Line 3 (Optional)', max_length=255, null=True)),
                ('city', models.CharField(default='', help_text='City', max_length=100)),
                ('state', models.CharField(default='', help_text='State', max_length=100)),
                ('country', models.CharField(default='India', help_text='Country', max_length=100)),
                ('pincode', models.CharField(default='', help_text='Pincode/Zip Code', max_length=20)),
                ('gstin', models.CharField(blank=True, help_text='GSTIN', max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
