# Generated by Django 5.0.14 on 2026-01-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventorylocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylocation',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['tenant_id', 'name'], name='inventory_m_tenant__9032d6_idx'),
        ),
        migrations.AlterModelTable(
            name='inventorylocation',
            table='inventory_master_location',
        ),
    ]
