# Generated by Django 5.0.14 on 2026-01-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventorylocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorystockitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='inventorystockitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='item',
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Vendor/Agent Name', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_code', models.CharField(help_text='Item Code', max_length=100)),
                ('item_name', models.CharField(help_text='Item Name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Item Description', null=True)),
                ('category_path', models.CharField(blank=True, help_text='Full category path display', max_length=500, null=True)),
                ('is_vendor_specific', models.BooleanField(default=False)),
                ('vendor_specific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_specific_suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('uom', models.CharField(help_text='Unit of Measure', max_length=50)),
                ('alternate_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('rate_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reorder_level', models.CharField(blank=True, max_length=255, null=True)),
                ('is_saleable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorymastercategory')),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroup_items', to='inventory.inventorymastercategory')),
            ],
            options={
                'db_table': 'inventory_master_inventoryitems',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='MasterVoucherGRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('voucher_name', models.CharField(help_text='Voucher name', max_length=100)),
                ('prefix', models.CharField(blank=True, help_text='Prefix for voucher number', max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, help_text='Suffix for voucher number', max_length=20, null=True)),
                ('start_from', models.IntegerField(default=1, help_text='Starting number')),
                ('current_number', models.IntegerField(default=1, help_text='Current number in sequence')),
                ('required_digits', models.IntegerField(default=4, help_text='Number of digits for padding')),
                ('enable_auto_numbering', models.BooleanField(default=True, help_text='Enable automatic numbering')),
                ('include_from_existing_series', models.CharField(blank=True, help_text='Include from existing series', max_length=200, null=True)),
                ('effective_from', models.DateField(blank=True, help_text='Effective from date', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Effective to date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'GRN Voucher Master',
                'verbose_name_plural': 'GRN Voucher Masters',
                'db_table': 'master_voucher_grn',
                'indexes': [models.Index(fields=['tenant_id'], name='master_vouc_tenant__84e701_idx'), models.Index(fields=['voucher_name'], name='master_vouc_voucher_0dcfe2_idx')],
            },
        ),
        migrations.CreateModel(
            name='MasterVoucherIssueSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('voucher_name', models.CharField(help_text='Voucher name', max_length=100)),
                ('prefix', models.CharField(blank=True, help_text='Prefix for voucher number', max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, help_text='Suffix for voucher number', max_length=20, null=True)),
                ('start_from', models.IntegerField(default=1, help_text='Starting number')),
                ('current_number', models.IntegerField(default=1, help_text='Current number in sequence')),
                ('required_digits', models.IntegerField(default=4, help_text='Number of digits for padding')),
                ('enable_auto_numbering', models.BooleanField(default=True, help_text='Enable automatic numbering')),
                ('include_from_existing_series', models.CharField(blank=True, help_text='Include from existing series', max_length=200, null=True)),
                ('effective_from', models.DateField(blank=True, help_text='Effective from date', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Effective to date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Issue Slip Voucher Master',
                'verbose_name_plural': 'Issue Slip Voucher Masters',
                'db_table': 'master_voucher_issue_slip',
                'indexes': [models.Index(fields=['tenant_id'], name='master_vouc_tenant__e3a763_idx'), models.Index(fields=['voucher_name'], name='master_vouc_voucher_481d3a_idx')],
            },
        ),
        migrations.DeleteModel(
            name='InventoryStockGroup',
        ),
        migrations.DeleteModel(
            name='InventoryStockItem',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant_id', 'item_code'], name='inventory_m_tenant__a62353_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_m_categor_85bc54_idx'),
        ),
    ]
