# Generated by Django 5.0.14 on 2026-01-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_inventorystockitem_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMasterGRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(default='GRN Series', help_text='GRN Series Name', max_length=255)),
                ('grn_type', models.CharField(default='other', help_text='GRN Type (job_work, purchase, import, other)', max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(default='2024', help_text='Year', max_length=4)),
                ('required_digits', models.IntegerField(default=4, help_text='Required Digits')),
                ('preview', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_master_grn',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMasterIssueSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(default='Issue Slip Series', help_text='Issue Slip Series Name', max_length=255)),
                ('issue_slip_type', models.CharField(default='other', help_text='Issue Slip Type (internal_transfer, customer_return, damage, other)', max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(default='2024', help_text='Year', max_length=4)),
                ('required_digits', models.IntegerField(default=4, help_text='Required Digits')),
                ('preview', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_master_issueslip',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='MasterVoucherGRN',
        ),
        migrations.DeleteModel(
            name='MasterVoucherIssueSlip',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(default='ITEM000', help_text='Item Code', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_name',
            field=models.CharField(default='New Item', help_text='Item Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='uom',
            field=models.CharField(default='nos', help_text='Unit of Measure', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='location_type',
            field=models.CharField(default='warehouse', help_text='Type of location (predefined or custom)', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='name',
            field=models.CharField(default='Main Location', help_text='Location name', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorymastercategory',
            name='category',
            field=models.CharField(default='General', help_text='Top-level category (e.g., RAW MATERIAL, Finished goods)', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='name',
            field=models.CharField(default='Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='symbol',
            field=models.CharField(default='nos', max_length=50),
        ),
    ]
