# Generated by Django 6.0 on 2026-01-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of PO series', max_length=100)),
                ('category', models.CharField(blank=True, help_text='Category of the PO Series', max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, help_text='Prefix for the PO Number, e.g., PO/', max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, help_text='Suffix for the PO Number, e.g., /2024', max_length=50, null=True)),
                ('auto_financial_year', models.BooleanField(default=True, help_text='Automatically include financial year')),
                ('digits', models.IntegerField(default=4, help_text='Number of digits for the sequence')),
                ('current_value', models.IntegerField(default=1, help_text='Next number in the sequence')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PO Series',
                'verbose_name_plural': 'PO Series',
                'db_table': 'vendors_po_series',
            },
        ),
    ]
