# Generated by Django 6.0 on 2026-01-13 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventorylocation_address_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poseries',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the PO Series', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_series', to='inventory.inventorycategory'),
        ),
    ]
