# Generated by Django 5.0.14 on 2026-01-17 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventorylocation'),
        ('vendors', '0002_alter_poseries_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMasterPOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('name', models.CharField(help_text='Name of PO Series', max_length=200)),
                ('prefix', models.CharField(blank=True, help_text='Prefix for PO number (e.g., PO/)', max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, help_text='Suffix for PO number (e.g., /24-25)', max_length=50, null=True)),
                ('digits', models.IntegerField(default=4, help_text='Number of digits for the sequence')),
                ('auto_year', models.BooleanField(default=False, help_text='Automatically include year in PO number')),
                ('current_number', models.IntegerField(default=1, help_text='Current sequence number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category for the PO Series', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_po_settings', to='inventory.inventorymastercategory')),
            ],
            options={
                'verbose_name': 'Vendor Master PO Setting',
                'verbose_name_plural': 'Vendor Master PO Settings',
                'db_table': 'vendor_master_posettings',
                'indexes': [models.Index(fields=['tenant_id'], name='vendor_mast_tenant__d7538b_idx'), models.Index(fields=['tenant_id', 'name'], name='vendor_mast_tenant__9e2a2a_idx')],
            },
        ),
    ]
