# Generated by Django 5.0.14 on 2026-01-17 07:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventorylocation'),
        ('vendors', '0003_vendormasterposettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('vendor_code', models.CharField(help_text='Unique vendor code', max_length=50, unique=True)),
                ('vendor_name', models.CharField(help_text='Vendor/Supplier name', max_length=200)),
                ('display_name', models.CharField(blank=True, help_text='Display name', max_length=200, null=True)),
                ('vendor_type', models.CharField(choices=[('supplier', 'Supplier'), ('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('service_provider', 'Service Provider'), ('other', 'Other')], default='supplier', help_text='Type of vendor', max_length=50)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary email address', max_length=255, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('mobile', models.CharField(blank=True, help_text='Mobile number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, help_text='Website URL', max_length=255, null=True)),
                ('billing_address_line1', models.CharField(blank=True, help_text='Billing address line 1', max_length=255, null=True)),
                ('billing_address_line2', models.CharField(blank=True, help_text='Billing address line 2', max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, help_text='Billing city', max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, help_text='Billing state', max_length=100, null=True)),
                ('billing_country', models.CharField(blank=True, help_text='Billing country', max_length=100, null=True)),
                ('billing_pincode', models.CharField(blank=True, help_text='Billing PIN/ZIP code', max_length=20, null=True)),
                ('shipping_address_line1', models.CharField(blank=True, help_text='Shipping address line 1', max_length=255, null=True)),
                ('shipping_address_line2', models.CharField(blank=True, help_text='Shipping address line 2', max_length=255, null=True)),
                ('shipping_city', models.CharField(blank=True, help_text='Shipping city', max_length=100, null=True)),
                ('shipping_state', models.CharField(blank=True, help_text='Shipping state', max_length=100, null=True)),
                ('shipping_country', models.CharField(blank=True, help_text='Shipping country', max_length=100, null=True)),
                ('shipping_pincode', models.CharField(blank=True, help_text='Shipping PIN/ZIP code', max_length=20, null=True)),
                ('gstin', models.CharField(blank=True, help_text='GSTIN number', max_length=15, null=True)),
                ('pan', models.CharField(blank=True, help_text='PAN number', max_length=10, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/VAT number', max_length=50, null=True)),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_45', 'Net 45 Days'), ('net_60', 'Net 60 Days'), ('net_90', 'Net 90 Days'), ('custom', 'Custom')], default='net_30', help_text='Payment terms', max_length=50)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit amount', max_digits=15, null=True)),
                ('credit_days', models.IntegerField(blank=True, help_text='Credit period in days', null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=200, null=True)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, help_text='IFSC code', max_length=20, null=True)),
                ('bank_branch', models.CharField(blank=True, help_text='Bank branch', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance', max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current outstanding balance', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Is vendor active')),
                ('is_verified', models.BooleanField(default=False, help_text='Is vendor verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Created by user', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Vendor category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='inventory.inventorymastercategory')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'ordering': ['vendor_name'],
                'indexes': [models.Index(fields=['tenant_id'], name='vendors_tenant__28cf36_idx'), models.Index(fields=['vendor_code'], name='vendors_vendor__656704_idx'), models.Index(fields=['tenant_id', 'vendor_name'], name='vendors_tenant__3fe37d_idx'), models.Index(fields=['tenant_id', 'is_active'], name='vendors_tenant__347159_idx')],
            },
        ),
    ]
