# Generated by Django 5.0.14 on 2026-01-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poseries',
            name='category',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendor_mast_tenant__caf7c0_idx',
            old_name='vendors_tenant__28cf36_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendor_mast_vendor__6a7a5a_idx',
            old_name='vendors_vendor__656704_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendor_mast_tenant__e535f8_idx',
            old_name='vendors_tenant__3fe37d_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendor_mast_tenant__6ec23e_idx',
            old_name='vendors_tenant__347159_idx',
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendor_master',
        ),
        migrations.DeleteModel(
            name='POSeries',
        ),
    ]
