# Generated by Django 5.0.14 on 2026-01-17 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_remove_poseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_ifsc',
            field=models.CharField(blank=True, help_text='IFSC code', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_country',
            field=models.CharField(default='India', help_text='Billing country', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_pincode',
            field=models.CharField(blank=True, help_text='Billing pincode', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='credit_days',
            field=models.IntegerField(blank=True, help_text='Credit days', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance', max_digits=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_country',
            field=models.CharField(default='India', help_text='Shipping country', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_pincode',
            field=models.CharField(blank=True, help_text='Shipping pincode', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax ID', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='VendorMasterBasicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('vendor_code', models.CharField(blank=True, help_text='Vendor code (auto-generated or manual)', max_length=50, null=True)),
                ('vendor_name', models.CharField(help_text='Vendor name', max_length=200)),
                ('pan_no', models.CharField(blank=True, help_text='PAN number', max_length=10, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Email address', max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('contact_no', models.CharField(help_text='Contact number', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number', regex='^\\+?1?\\d{9,15}$')])),
                ('is_also_customer', models.BooleanField(default=False, help_text='Is this vendor also a customer?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Created by user', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Vendor Master Basic Detail',
                'verbose_name_plural': 'Vendor Master Basic Details',
                'db_table': 'vendor_master_basicdetail',
                'indexes': [models.Index(fields=['tenant_id'], name='vendor_mast_tenant__54ee94_idx'), models.Index(fields=['tenant_id', 'vendor_name'], name='vendor_mast_tenant__8e6136_idx'), models.Index(fields=['email'], name='vendor_mast_email_1429e2_idx'), models.Index(fields=['pan_no'], name='vendor_mast_pan_no_5aba7c_idx')],
                'unique_together': {('tenant_id', 'vendor_code')},
            },
        ),
    ]
