# Generated by Django 5.0.14 on 2026-01-17 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_add_vendor_basicdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMasterGSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('gstin', models.CharField(help_text='GSTIN number (15 characters)', max_length=15)),
                ('gst_registration_type', models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition'), ('unregistered', 'Unregistered'), ('consumer', 'Consumer'), ('overseas', 'Overseas'), ('special_economic_zone', 'Special Economic Zone'), ('deemed_export', 'Deemed Export')], default='regular', help_text='GST registration type', max_length=50)),
                ('legal_name', models.CharField(help_text='Legal name as per GST', max_length=200)),
                ('trade_name', models.CharField(blank=True, help_text='Trade/Brand name', max_length=200, null=True)),
                ('gst_state', models.CharField(blank=True, help_text='State of GST registration', max_length=100, null=True)),
                ('gst_state_code', models.CharField(blank=True, help_text='State code (2 digits)', max_length=2, null=True)),
                ('pan_linked_with_gstin', models.CharField(blank=True, help_text='PAN linked with GSTIN', max_length=10, null=True)),
                ('date_of_registration', models.DateField(blank=True, help_text='Date of GST registration', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Created by user', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True)),
                ('vendor_basic_detail', models.ForeignKey(blank=True, help_text='Link to vendor basic details', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_details', to='vendors.vendormasterbasicdetail')),
            ],
            options={
                'verbose_name': 'Vendor Master GST Detail',
                'verbose_name_plural': 'Vendor Master GST Details',
                'db_table': 'vendor_master_gstdetails',
                'indexes': [models.Index(fields=['tenant_id'], name='vendor_mast_tenant__0b54ec_idx'), models.Index(fields=['gstin'], name='vendor_mast_gstin_6a2716_idx'), models.Index(fields=['tenant_id', 'gstin'], name='vendor_mast_tenant__be992f_idx')],
                'unique_together': {('tenant_id', 'gstin')},
            },
        ),
        migrations.CreateModel(
            name='VendorMasterProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('hsn_sac_code', models.CharField(blank=True, help_text='HSN or SAC Code', max_length=20, null=True)),
                ('item_code', models.CharField(blank=True, help_text='Internal Item Code', max_length=50, null=True)),
                ('item_name', models.CharField(help_text='Internal Item Name', max_length=200)),
                ('supplier_item_code', models.CharField(blank=True, help_text="Supplier's Item Code", max_length=50, null=True)),
                ('supplier_item_name', models.CharField(blank=True, help_text="Supplier's Item Name", max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Created by user', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True)),
                ('vendor_basic_detail', models.ForeignKey(blank=True, help_text='Link to vendor basic details', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_services', to='vendors.vendormasterbasicdetail')),
            ],
            options={
                'verbose_name': 'Vendor Master Product/Service',
                'verbose_name_plural': 'Vendor Master Products/Services',
                'db_table': 'vendor_master_productservices',
                'indexes': [models.Index(fields=['tenant_id'], name='vendor_mast_tenant__d1daf1_idx'), models.Index(fields=['vendor_basic_detail'], name='vendor_mast_vendor__9ef8bc_idx'), models.Index(fields=['item_code'], name='vendor_mast_item_co_39aed3_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorMasterTDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('pan_number', models.CharField(blank=True, help_text='PAN Number', max_length=10, null=True)),
                ('tan_number', models.CharField(blank=True, help_text='TAN Number', max_length=10, null=True)),
                ('tds_section', models.CharField(blank=True, help_text='TDS Section (e.g., 194C, 194J)', max_length=50, null=True)),
                ('tds_rate', models.DecimalField(blank=True, decimal_places=2, help_text='TDS Rate in percentage', max_digits=5, null=True)),
                ('tds_section_applicable', models.CharField(blank=True, help_text='TDS Section Applicable', max_length=100, null=True)),
                ('enable_automatic_tds_posting', models.BooleanField(default=False, help_text='Enable automatic TDS posting')),
                ('msme_udyam_no', models.CharField(blank=True, help_text='MSME Udyam Registration Number', max_length=50, null=True)),
                ('fssai_license_no', models.CharField(blank=True, help_text='FSSAI License Number', max_length=50, null=True)),
                ('import_export_code', models.CharField(blank=True, help_text='Import Export Code (IEC)', max_length=50, null=True)),
                ('eou_status', models.CharField(blank=True, help_text='Export Oriented Unit Status', max_length=100, null=True)),
                ('cin_number', models.CharField(blank=True, help_text='Corporate Identification Number', max_length=21, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Created by user', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True)),
                ('vendor_basic_detail', models.ForeignKey(blank=True, help_text='Link to vendor basic details', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_details', to='vendors.vendormasterbasicdetail')),
            ],
            options={
                'verbose_name': 'Vendor Master TDS Detail',
                'verbose_name_plural': 'Vendor Master TDS Details',
                'db_table': 'vendor_master_tds',
                'indexes': [models.Index(fields=['tenant_id'], name='vendor_mast_tenant__9451a1_idx'), models.Index(fields=['vendor_basic_detail'], name='vendor_mast_vendor__f1c0fd_idx'), models.Index(fields=['pan_number'], name='vendor_mast_pan_num_7acca3_idx')],
            },
        ),
    ]
