# Generated by Django 5.0.14 on 2026-01-17 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendormastergstdetails_vendormasterproductservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMasterBanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('bank_account_no', models.CharField(help_text='Bank Account Number', max_length=50)),
                ('bank_name', models.CharField(help_text='Bank Name', max_length=200)),
                ('ifsc_code', models.CharField(help_text='IFSC Code', max_length=11)),
                ('branch_name', models.CharField(blank=True, help_text='Branch Name', max_length=200, null=True)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT Code (for international transactions)', max_length=11, null=True)),
                ('vendor_branch', models.CharField(blank=True, help_text='Associate to a vendor branch', max_length=200, null=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('cash_credit', 'Cash Credit'), ('overdraft', 'Overdraft')], default='current', help_text='Type of bank account', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Created by user', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True)),
                ('vendor_basic_detail', models.ForeignKey(blank=True, help_text='Link to vendor basic details', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banking_details', to='vendors.vendormasterbasicdetail')),
            ],
            options={
                'verbose_name': 'Vendor Master Banking Detail',
                'verbose_name_plural': 'Vendor Master Banking Details',
                'db_table': 'vendor_master_banking',
                'indexes': [models.Index(fields=['tenant_id'], name='vendor_mast_tenant__818fc5_idx'), models.Index(fields=['vendor_basic_detail'], name='vendor_mast_vendor__9eae55_idx'), models.Index(fields=['bank_account_no'], name='vendor_mast_bank_ac_062bce_idx')],
            },
        ),
    ]
