# Generated by Django 5.0.14 on 2026-01-17 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendormasterbanking'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMasterTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit amount', max_digits=15, null=True)),
                ('credit_period', models.CharField(blank=True, help_text='Credit period (e.g., 30 days, 60 days)', max_length=100, null=True)),
                ('credit_terms', models.TextField(blank=True, help_text='Credit terms and conditions', null=True)),
                ('penalty_terms', models.TextField(blank=True, help_text='Penalty terms for late payments or breaches', null=True)),
                ('delivery_terms', models.TextField(blank=True, help_text='Delivery terms, lead time, shipping conditions', null=True)),
                ('warranty_guarantee_details', models.TextField(blank=True, help_text='Warranty and guarantee terms', null=True)),
                ('force_majeure', models.TextField(blank=True, help_text='Force majeure clauses', null=True)),
                ('dispute_redressal_terms', models.TextField(blank=True, help_text='Dispute resolution and redressal terms', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Created by user', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True)),
                ('vendor_basic_detail', models.ForeignKey(blank=True, help_text='Link to vendor basic details', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='vendors.vendormasterbasicdetail')),
            ],
            options={
                'verbose_name': 'Vendor Master Terms & Conditions',
                'verbose_name_plural': 'Vendor Master Terms & Conditions',
                'db_table': 'vendor_master_terms',
                'indexes': [models.Index(fields=['tenant_id'], name='vendor_mast_tenant__3d7d87_idx'), models.Index(fields=['vendor_basic_detail'], name='vendor_mast_vendor__95626c_idx')],
            },
        ),
    ]
