# Generated by Django 5.0.14 on 2026-01-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendormasterterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTransactionPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('po_number', models.CharField(help_text='Purchase Order Number', max_length=50)),
                ('vendor_name', models.CharField(blank=True, help_text='Vendor name', max_length=200, null=True)),
                ('branch', models.CharField(blank=True, help_text='Vendor branch', max_length=200, null=True)),
                ('address_line1', models.CharField(blank=True, help_text='Address Line 1', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, help_text='Address Line 2', max_length=255, null=True)),
                ('address_line3', models.CharField(blank=True, help_text='Address Line 3', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, help_text='Pincode', max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, help_text='Email Address', max_length=255, null=True)),
                ('contract_no', models.CharField(blank=True, help_text='Contract Number', max_length=100, null=True)),
                ('receive_by', models.DateField(blank=True, help_text='Expected receive date', null=True)),
                ('receive_at', models.CharField(blank=True, help_text='Receive at location', max_length=200, null=True)),
                ('delivery_terms', models.TextField(blank=True, help_text='Delivery terms and conditions', null=True)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total taxable value', max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax amount', max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total PO value', max_digits=15)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Mailed', 'Mailed'), ('Closed', 'Closed')], default='Draft', help_text='PO Status', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Created by user', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Updated by user', max_length=100, null=True)),
                ('po_series', models.ForeignKey(blank=True, help_text='PO Series configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='vendors.vendormasterposettings')),
                ('vendor_basic_detail', models.ForeignKey(blank=True, help_text='Link to vendor basic details', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='vendors.vendormasterbasicdetail')),
            ],
            options={
                'verbose_name': 'Vendor Purchase Order',
                'verbose_name_plural': 'Vendor Purchase Orders',
                'db_table': 'vendor_transaction_po',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorTransactionPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36)),
                ('item_code', models.CharField(blank=True, help_text='Item code', max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, help_text='Item name', max_length=200, null=True)),
                ('supplier_item_code', models.CharField(blank=True, help_text='Supplier item code', max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity', max_digits=10)),
                ('uom', models.CharField(blank=True, help_text='Unit of Measurement', max_length=20, null=True)),
                ('negotiated_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Negotiated rate', max_digits=15)),
                ('final_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Final rate', max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxable value', max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='GST rate percentage', max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='GST amount', max_digits=15)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total invoice value', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po', models.ForeignKey(help_text='Link to purchase order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendors.vendortransactionpo')),
            ],
            options={
                'verbose_name': 'Vendor PO Item',
                'verbose_name_plural': 'Vendor PO Items',
                'db_table': 'vendor_transaction_po_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='vendortransactionpo',
            index=models.Index(fields=['tenant_id'], name='vendor_tran_tenant__c49b20_idx'),
        ),
        migrations.AddIndex(
            model_name='vendortransactionpo',
            index=models.Index(fields=['po_number'], name='vendor_tran_po_numb_80a0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='vendortransactionpo',
            index=models.Index(fields=['tenant_id', 'po_number'], name='vendor_tran_tenant__6aafe1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendortransactionpo',
            index=models.Index(fields=['status'], name='vendor_tran_status_c27e56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendortransactionpo',
            unique_together={('tenant_id', 'po_number')},
        ),
        migrations.AddIndex(
            model_name='vendortransactionpoitem',
            index=models.Index(fields=['tenant_id'], name='vendor_tran_tenant__5d89e7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendortransactionpoitem',
            index=models.Index(fields=['po'], name='vendor_tran_po_id_48ad29_idx'),
        ),
    ]
