# Generated by Django 5.0.14 on 2026-01-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendortransactionpo_vendortransactionpoitem_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendormastertds',
            name='vendor_mast_pan_num_7acca3_idx',
        ),
        migrations.RemoveField(
            model_name='vendormastertds',
            name='cin_number',
        ),
        migrations.RemoveField(
            model_name='vendormastertds',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='vendormastertds',
            name='tan_number',
        ),
        migrations.RemoveField(
            model_name='vendormastertds',
            name='tds_rate',
        ),
        migrations.RemoveField(
            model_name='vendormastertds',
            name='tds_section',
        ),
    ]
