# Generated by Django 5.0.14 on 2026-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_remove_tds_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(help_text='Top-level category (e.g., Raw material, Stores and Spares, Packing Material)', max_length=255)),
                ('group', models.CharField(blank=True, help_text='Group under category (optional)', max_length=255, null=True)),
                ('subgroup', models.CharField(blank=True, help_text='Subgroup under group (optional)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vendor_master_category',
                'ordering': ['category', 'group', 'subgroup'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='vendor_mast_tenant__1486a9_idx'), models.Index(fields=['category'], name='vendor_mast_categor_679661_idx')],
                'unique_together': {('tenant_id', 'category', 'group', 'subgroup')},
            },
        ),
    ]
