# Generated by Django 5.0.14 on 2026-01-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_add_vendor_master_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormastergstdetails',
            name='branch_address',
            field=models.TextField(blank=True, help_text='Branch address', null=True),
        ),
        migrations.AddField(
            model_name='vendormastergstdetails',
            name='branch_contact_no',
            field=models.CharField(blank=True, help_text='Branch contact number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendormastergstdetails',
            name='branch_contact_person',
            field=models.CharField(blank=True, help_text='Branch contact person', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendormastergstdetails',
            name='branch_email',
            field=models.CharField(blank=True, help_text='Branch email', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendormastergstdetails',
            name='reference_name',
            field=models.CharField(blank=True, help_text='Branch reference name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendormastercategory',
            name='category',
            field=models.CharField(help_text='Top-level category (e.g., RAW MATERIAL, Stores and Spares, Packing Material)', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendormastercategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendormastercategory',
            name='tenant_id',
            field=models.CharField(help_text='Tenant ID for multi-tenancy', max_length=36),
        ),
        migrations.AlterField(
            model_name='vendormastercategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
