# Generated by Django 5.0.14 on 2026-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_vendormastergstdetails_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormastertds',
            name='eou_file',
            field=models.FileField(blank=True, help_text='EOU Certificate', null=True, upload_to='vendors/eou/'),
        ),
        migrations.AddField(
            model_name='vendormastertds',
            name='fssai_file',
            field=models.FileField(blank=True, help_text='FSSAI License', null=True, upload_to='vendors/fssai/'),
        ),
        migrations.AddField(
            model_name='vendormastertds',
            name='import_export_file',
            field=models.FileField(blank=True, help_text='IEC Certificate', null=True, upload_to='vendors/iec/'),
        ),
        migrations.AddField(
            model_name='vendormastertds',
            name='msme_file',
            field=models.FileField(blank=True, help_text='MSME Certificate', null=True, upload_to='vendors/msme/'),
        ),
    ]
