# Generated by Django 5.2.9 on 2026-01-20 08:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_employee_basic_details',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='payroll_emp_tenant__3c85ef_idx'), models.Index(fields=['employee_code'], name='payroll_emp_employe_d77d0c_idx')],
                'unique_together': {('tenant_id', 'employee_code')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='payroll.employeebasicdetails')),
            ],
            options={
                'db_table': 'payroll_employee_bank_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='payroll.employeebasicdetails')),
            ],
            options={
                'db_table': 'payroll_employee_employment',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='payroll.employeebasicdetails')),
            ],
            options={
                'db_table': 'payroll_employee_salary',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatutory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('uan_number', models.CharField(blank=True, max_length=12, null=True)),
                ('esi_number', models.CharField(blank=True, max_length=17, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statutory', to='payroll.employeebasicdetails')),
            ],
            options={
                'db_table': 'payroll_employee_statutory',
            },
        ),
    ]
