# Generated by Django 5.0.14 on 2026-01-21 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebankdetails',
            name='employee_basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='payroll.employeebasicdetails'),
        ),
    ]
