# Generated by Django 5.0.14 on 2026-01-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_employeebankdetails_employee_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='employeebasicdetails',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='salarytemplate',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='statutoryconfiguration',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
