# Generated by Django 5.2.9 on 2026-01-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employeebasicdetails_employeebankdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasicdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
