# Generated by Django 5.0.14 on 2026-01-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleModule',
        ),
        migrations.DeleteModel(
            name='TenantUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_status',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
    ]
