# Generated by Django 6.0 on 2025-12-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companysettings_delete_ledger_delete_voucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
