# Generated by Django 5.0.14 on 2025-12-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_role_alter_user_id_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyInformation',
        ),
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
    ]
