# Generated by Django 5.0.14 on 2025-12-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_otpratelimit_user_phone_user_phone_verified_otp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRateLimit',
        ),
        migrations.DeleteModel(
            name='PendingRegistration',
        ),
    ]
