# Generated by Django 5.0.14 on 2025-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_otpratelimit_delete_pendingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('selected_plan', models.CharField(max_length=50)),
                ('logo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pending_registrations',
                'indexes': [models.Index(fields=['phone'], name='pending_reg_phone_961a12_idx'), models.Index(fields=['expires_at'], name='pending_reg_expires_f06591_idx')],
            },
        ),
    ]
