# Generated by Django 5.0.14 on 2025-12-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_permissionmodule_permissionsubmodule_and_more'),
    ]

    operations = [
        # migrations.RunSQL(
        #     sql="DROP TABLE IF EXISTS journal_entries;",
        #     reverse_sql="-- Cannot reverse this migration. Table journal_entries was unused.",
        # ),
    ]
