# Generated by Django 6.0 on 2025-12-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_journal_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=36)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='tenant_users', to='core.role')),
            ],
            options={
                'db_table': 'tenant_users',
            },
        ),
    ]
