# Generated by Django 6.0 on 2025-12-15 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tenantuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_users', to='core.role'),
        ),
    ]
