# Generated by Django 5.0.14 on 2025-12-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_mobile_field'),
        ('core', '0017_remove_permissions_add_submodule_ids'),
    ]

    operations = [
    ]
