# Generated by Django 5.0.14 on 2026-01-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_missing_company_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_module_id', models.IntegerField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['parent_module_id', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('module_id', models.IntegerField()),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role_modules',
            },
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.RemoveField(
            model_name='permissionsubmodule',
            name='module',
        ),
        migrations.RemoveField(
            model_name='rolesubmodulepermission',
            name='submodule',
        ),
        migrations.AlterUniqueTogether(
            name='rolesubmodulepermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolesubmodulepermission',
            name='role',
        ),
        migrations.AddField(
            model_name='companyfullinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfullinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='role_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='selected_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='unique_role_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='rolemodule',
            index=models.Index(fields=['role_id'], name='idx_role_id'),
        ),
        migrations.AddIndex(
            model_name='rolemodule',
            index=models.Index(fields=['module_id'], name='idx_module_id'),
        ),
        migrations.AddConstraint(
            model_name='rolemodule',
            constraint=models.UniqueConstraint(fields=('role_id', 'module_id'), name='unique_role_module'),
        ),
        migrations.DeleteModel(
            name='PermissionModule',
        ),
        migrations.DeleteModel(
            name='PermissionSubmodule',
        ),
        migrations.DeleteModel(
            name='RoleSubmodulePermission',
        ),
    ]
