# Generated by Django 5.0.14 on 2026-01-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_module_rolemodule_delete_otp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingRegistration',
        ),
    ]
